---
- name: Apply common configurations
  hosts: all
  become: true
  roles:
  - role: common
  - role: network_config
  - role: geerlingguy.docker
  - role: docker_permissions
  - role: beszel
  - role: beszel_agent
  - role: tailscale
