---
- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 43200 # 12 hours in seconds
    upgrade: dist

- name: Disable UFW
  ansible.builtin.ufw:
    state: disabled
